In [2]:
import tensorflow as tf

In [47]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.feature_selection import SelectKBest
from sklearn.dummy import DummyClassifier
from sklearn.model_selection import RandomizedSearchCV
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.feature_selection import VarianceThreshold
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import f_classif

In [3]:
fashion_mnist=tf.keras.datasets.fashion_mnist

In [4]:
(X_train,y_train),(X_test,y_test)=fashion_mnist.load_data()

In [5]:
test=np.array(X_test)

In [6]:
test.shape=(10000,28*28)

In [7]:
test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [8]:
train=np.array(X_train)

In [9]:
train.shape=(60000,784)

In [10]:
train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [20]:
df=pd.DataFrame(train)

In [21]:
df

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  \
0        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        0    0    0    0    0    1    0    0    0    0  ...  119  114  130   
2        0    0    0    0    0    0    0    0    0   22  ...    0    0    1   
3        0    0    0    0    0    0    0    0   33   96  ...    0    0    0   
4        0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
59995    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59996    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   
59997    0    0    0    0    0    0    0    0    0    5  ...    0    0    0   
59998    0    0    0    0    0    0    0    0    0    0  ...   66   54   50   
59999    0    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       777  778  779  780  781  782  783  
0        0    0    0    0    0    0    0  
1       76    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
59995    0    0    0    0    0    0    0  
59996    0    0    0    0    0    0    0  
59997    0    0    0    0    0    0    0  
59998    5    0    1    0    0    0    0  
59999    0    0    0    0    0    0    0  

[60000 rows x 784 columns]

# Set the figure size
plt.figure(figsize=(10,10))
input_data=df.iloc[:,1:]/255
# Show only the first 30 pictures
for i in range(30):
    plt.subplot(6,5, i+1)
    plt.xticks([])
    plt.yticks([])
    plt.imshow(np.array(input_data.iloc[i, :]).reshape(28,28), cmap=plt.cm.binary)
    plt.xlabel(label[target.label.iloc[i]])

In [13]:
# dummy model, to see what a "bad score" would look like

dummy_model = DummyClassifier()
dummy_model.fit(train,y_train)

DummyClassifier()

In [14]:
dummy_model.score(test,y_test)

0.1

In [42]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(train,y_train, test_size=0.2, random_state=25)

not good

In [43]:
decision_tree = DecisionTreeClassifier()
decision_tree =decision_tree.fit(X_train2,y_train2)

In [44]:
decision_tree.score(X_test2,y_test2)

0.7973333333333333

In [82]:
def select_features(X_train, y_train, X_test,i):
    
    # configure to select a subset of features
    fs = SelectKBest(score_func=f_classif, k=i)
    
    # learn relationship from training data
    fs.fit(X_train, y_train)
    
    # transform train input data
    X_train_fs = fs.transform(X_train)
    
    # transform test input data
    X_test_fs = fs.transform(X_test)
        
    return X_train_fs, X_test_fs, fs

In [83]:
X_train_fs, X_test_fs, fs = select_features(X_train2, y_train2, X_test2,600)

In [74]:
decision_tree = DecisionTreeClassifier()
decision_tree =decision_tree.fit(X_train_fs,y_train2)

0.79875-700

0.7999166666666667-600

0.7940833333333334-500

0.7936666666666666-550

0.79475-575


In [75]:
decision_tree.score(X_test_fs,y_test2)

0.7993333333333333

In [99]:
X_train_fs, X_test_fs, fs = select_features(X_train2, y_train2, X_test2,600)

In [97]:
knn = KNeighborsClassifier()

knn.fit(X_train2,y_train2)

KNeighborsClassifier()

In [100]:
knn2 = KNeighborsClassifier()

knn2.fit(X_train_fs,y_train2)

KNeighborsClassifier()

In [101]:
knn2.score(X_test_fs,y_test2)

0.8514166666666667

In [44]:
cross_val_score(knn,train,y_train,cv=5)

array([0.85741667, 0.84875   , 0.85358333, 0.85875   , 0.8515    ])

In [98]:
knn.score(X_test2,y_test2)

0.85125

In [47]:
model = AdaBoostClassifier()
# evaluate the model
#cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
model.fit(train,y_train)

AdaBoostClassifier()

In [49]:
model.score(test,y_test)


0.5425